name:                tweetdelete
version:             0.1.0.0
github:              "githubuser/tweetdelete"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tweetdelete#readme>

dependencies:
- base >= 4.7 && < 5
- twitter-conduit
- optparse-applicative
- twitter-types
- time
- text
- mtl

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -XEmptyCase
    - -XInstanceSigs
    - -XLambdaCase
    - -XMultiWayIf
    - -XNamedFieldPuns
    - -XTupleSections
    - -XBangPatterns
    - -XKindSignatures
    - -XTypeOperators
    - -XOverloadedStrings
    - -XScopedTypeVariables
    - -XTypeApplications
    - -XApplicativeDo
    - -XDeriveGeneric
    - -XDataKinds
    - -XDerivingVia
    - -XRecordWildCards
    - -XDeriveFunctor
    - -XDeriveTraversable
   

library:
  source-dirs: src

executables:
  tweetdelete-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tweetdelete

tests:
  tweetdelete-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tweetdelete
