name:                tweetdelete
version:             0.1.0.0
license:             BSD3
author:              "Tilde Rose"
maintainer:          "t1lde@protonmail.com"
copyright:           "2020 Tilde Rose"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Delete tweets from the commandline using the Twitter API (via twitter-conduit)
category:            Web

description:         Please see the README on GitLab at <https://gitlab.com/t1lde/tweetdelete_hs#readme>

dependencies:
- base >= 4.7 && < 5
- twitter-conduit
- optparse-applicative
- twitter-types
- twitter-types-lens
- time
- text
- bytestring
- mtl
- transformers
- attoparsec
- authenticate-oauth
- lens
- conduit
- conduit-extra
- parallel-io

ghc-options:
    - -O2
    - -Wall
    - -Werror
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -XEmptyCase
    - -XInstanceSigs
    - -XLambdaCase
    - -XMultiWayIf
    - -XNamedFieldPuns
    - -XTupleSections
    - -XBangPatterns
    - -XKindSignatures
    - -XTypeOperators
    - -XOverloadedStrings
    - -XScopedTypeVariables
    - -XTypeApplications
    - -XApplicativeDo
    - -XDeriveGeneric
    - -XDataKinds
    - -XDerivingVia
    - -XRecordWildCards
    - -XDeriveFunctor
    - -XDeriveTraversable
    - -XOverloadedLabels

library:
  source-dirs: src

executables:
  tweetdelete-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tweetdelete

tests:
  tweetdelete-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tweetdelete
